### ISSUE TITLE
Use tempfile module

### ISSUE THREAD

**Issue by flungo** [flungo-ansible/aur#1]
When Ansible 2.3 is release, use the tempfile module instead of the command module.

```
- name: Create a temporary directory for AUR packages
  tempfile:
    state: directory
    suffix: aur
  register: tempdir_aur
  when: which_pacaur|failed
```
